---
abstract: 'TokyoTyrant plugin for Lingua::JA::WebIDF'
author:
  - 'pawa <pawapawa@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Spec: 0
  Test::Fatal: 0
  Test::More: 0.88
  Test::Requires: 0
  Test::TCP: 1.15
  Test::ttserver: 0.003
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-JA-WebIDF-Driver-TokyoTyrant
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Carp: 0
  Lingua::JA::WebIDF: 0.31
  TokyoTyrant: 0
  perl: 5.8.1
resources:
  bugtracker: https://github.com/pawa-/Lingua-JA-WebIDF-Driver-TokyoTyrant/issues
  license: http://dev.perl.org/licenses
  repository: https://github.com/pawa-/Lingua-JA-WebIDF-Driver-TokyoTyrant
version: 0.01
